from runner import exceptions


def test_logged_exception_logs_correct_message():
    assert 1 == 1

